openapi: 3.0.0
info:
  title: PingOne Platform API - PingOne Risk
  description: The PingOne Platform API covering the PingOne Risk service
  version: 1.0.0
externalDocs:
  url: https://apidocs.pingidentity.com/pingone/platform/v1/api/#pingone-risk
  description: PingOne Platform API Reference - PingOne Risk APIs
servers:
  - url: https://api.pingone.{suffix}
    description: PingOne Platform API Endpoint
    variables:
      suffix:
        enum:
          - 'eu'
          - 'com'
          - 'asia'
          - 'ca'
        default: 'eu'
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: OAuth bearer token (see documentation)
  schemas:
    P1Error:
      type: object
      properties: 
        id:
          type: string
        code:
          type: string
        message:
          type: string
        details:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              target:
                type: string
              message:
                type: string
    EntityArray:
      type: object
      properties:
        '_embedded':
          type: object
          properties:
            riskPolicySets:
              type: array
              items:
                $ref: '#/components/schemas/RiskPolicySet'
            riskPredictors:
              type: array
              items:
                $ref: '#/components/schemas/RiskPredictor'
        count:
          type: number
        size:
          type: number
    ObjectEnvironment:
      type: object
      readOnly: true
      properties:
        id:
          type: string
          readOnly: true
          description: A string that specifies the environment associated with the object.
    RiskEvaluation:
      type: object
      properties:
        createdAt:
          type: string
          readOnly: true
          description: The time the resource was created (format ISO-8061).
        details:
          $ref: '#/components/schemas/RiskEvaluationDetails'
          readOnly: true
          description: A details object that provides additional information about the risk evaluation.
        environment:
          $ref: '#/components/schemas/ObjectEnvironment'
        event:
          $ref: '#/components/schemas/RiskEvaluationEvent'
          description: An object that specifies the attributes to identify the event. This is a required property. For more information about event attributes, see the Event Data Model table.
        id:
          type: string
          readOnly: true
          description: A string that specifies the resourceâ€™s unique identifier.
        riskPolicySet:
          type: object
          properties:
            id:
              type: string
              description: A string that specifies the risk policy set resource's unique identifier. If the risk policy set ID and name are both specified, the policy set specified by the riskPolicySet.id is used. If the risk policy set ID and name are not specified, the environment's default risk policy set is used.
            name:
              type: string
              description: A string that specifies the risk policy set name associated with this risk evaluation resource. If the risk policy set ID and name are both specified, the policy set specified by the riskPolicySet.id is used. If the risk policy set name and ID are not specified, the environment's default risk policy set is used.
        result:
          $ref: '#/components/schemas/RiskEvaluationResult'
          readOnly: true
          description: A result object that specifies the result that corresponds to the risk policy that evaluates as true. If there are several risk policies that evaluate as true, the result that corresponds to the highest priority risk policy is returned. If no risk policy evaluates as true, the result is the defaultResult of the policy set.
        updatedAt:
          type: string
          readOnly: true
          description: The time the resource was last updated (format ISO-8061).
      required:
        - event
    RiskEvaluationDetails:
      type: object
      readOnly: true
      properties:
        ipAddressReputation:
          type: object
          properties: 
            level:
              type: string
              enum: [LOW, MEDIUM, HIGH]
              description: A string that specifies the risk level of the evaluated IP address. Options are LOW, MEDIUM, and HIGH. If the score is less than 55, the level is LOW; if the score is greater than 77, the level is HIGH; if the score is between 55 and 77, the level is MEDIUM. Note that these guidelines could change based on data analytics and product consideration. If the ipAddressReputation.score is unknown, NULL is returned.
            score:
              type: integer
              description: An integer that represents the calculated score of the IP address involved in the transaction. Scores range between 0 and 100. A score of 0 indicates a non-risky IP address; a score of 100 indicates a high-risk IP address. If the IP address reputation score is not available for the specific IP address, NULL is returned.
        ipVelocityByUser:
          type: object
          properties: 
            level:
              type: string
              enum: [LOW, MEDIUM, HIGH]
              description: An enum indicating whether the number of distinct IPs for the user in the past hour is flagged as LOW, MEDIUM, or HIGH.
            reason:
              type: string
              description: A string indicating the reason the user was flagged. For example "More than 13 IPs were accessed by John during the last 1 hour."
            threshold:
              type: object
              description: The information about the threshold used.
              properties:
                high:
                  type: integer
                  description: An integer indicating the value calculated for the high threshold. If the user accessed more than the high number of IPs during the past hour, they're flagged as a HIGH ipVelocityByUser.level.
                medium:
                  type: integer
                  description: An integer indicating the value calculated for the medium threshold. If the user accessed more than the medium number of IPs during the past hour, they're flagged as a MEDIUM ipVelocityByUser.level.
                source:
                  type: string
                  enum: [MIN_NOT_REACHED, CALCULATED, ENVIRONMENT_FALLBACK, DEFAULT_FALLBACK]
                  description:  >-
                    An enum indicating the source used to calculate the threshold. This can be
                    MIN_NOT_REACHED. If the measure is less than every.minSample, the threshold isn't calculated. Instead, a value of LOW is automatically assigned. If less than five IPs were used by the user during the past hour, MIN_NOT_REACHED is set.
                    CALCULATED. Indicates the threshold is guaranteed to be calculated.
                    ENVIRONMENT_FALLBACK. Indicates a global threshold calculated for the entire environment is used. The global threshold is used when the ipVelocityByUser.threshold couldn't be calculated, generally due to a lack of past transactions for the risk predictor to use for the threshold calculation.
                    DEFAULT_FALLBACK. Indicates the default threshold defined for the predictor (in threshold.medium or threshold.high) is used. The default threshold is used when ENVIRONMENT_FALLBACK (the global threshold) couldn't be calculated, generally due to a lack of past transactions for the risk predictor to use for the environment threshold calculation.
                calculatedAt:
                  type: string
                  description: A date-time indicating the timestamp for the calculated threshold.
                expiresAt:
                  type: string
                  description: A date-time indicating when the threshold will be recalculated. The recalculation will happen before this time.
            velocity:
              type: object
              description: Integer values for the measures used to calculate velocity.
              properties:
                distinctCount:
                  type: integer
                  description: This is the distinct count for the previous seconds indicated by the during value.
                during:
                  type: integer
                  description: The interval (in seconds) during which the velocity is calculated.
        userVelocityByIp:
          type: object
          properties: 
            level:
              type: string
              enum: [LOW, MEDIUM, HIGH]
              description: An enum indicating whether the calculated number of users per IP is LOW, MEDIUM, or HIGH.
            reason:
              type: string
              description: A string indicating the reason the user was flagged. For example "More than 250 users accessed IP address 1.1.1.1 during the last 1 hour."
            threshold:
              type: object
              description: The information about the calculated threshold used.
              properties:
                high:
                  type: integer
                  description: An integer indicating the value calculated for the high threshold. If the IP was accessed by more than the high number of users during the past hour, the IP is flagged as a HIGH userVelocityByIp.level.
                medium:
                  type: integer
                  description: An integer indicating the value calculated for the medium threshold. If the IP was accessed by more than the medium number of users during the past hour, the IP is flagged as a MEDIUM userVelocityByIp.level
                source:
                  type: string
                  enum: [MIN_NOT_REACHED, CALCULATED, ENVIRONMENT_FALLBACK, DEFAULT_FALLBACK]
                  description:  >-
                    An enum indicating the source used to calculate the threshold. This can be:
                    MIN_NOT_REACHED. If the measure is less than every.minSample, the threshold isn't calculated. Instead, a value of LOW is automatically assigned.
                    CALCULATED. Indicates the threshold was calculated.
                    ENVIRONMENT_FALLBACK. Indicates a global threshold calculated for the entire environment is used. The global threshold is used when the userVelocityByIp.threshold couldn't be calculated for the user, generally due to a lack of past transactions for the risk predictor to use for the threshold calculation.
                    DEFAULT_FALLBACK. Indicates the default threshold defined for the predictor (in threshold.medium or threshold.high) is used. The default threshold is used when ENVIRONMENT_FALLBACK (the global threshold) couldn't be calculated, generally due to a lack of past transactions for the risk predictor to use for the global threshold calculation.
                calculatedAt:
                    type: string
                    description: A date-time indicating the timestamp for the calculated threshold.
                expiresAt:
                    type: string
                    description: A date-time indicating when the threshold will be recalculated. The recalculation will happen before this time.
            velocity:
              type: object
              description: Integer values for the measures used to calculate velocity.
              properties:
                distinctCount:
                  type: integer
                  description: Relevant only for predictors having a measure value of "DISTINCT_COUNT". This is the number of users that accessed the IP in the past during seconds.
                during:
                  type: integer
                  description: The interval (in seconds) during which the velocity is calculated.
        impossibleTravel:
          type: boolean
          description: >-
            A boolean that specifies whether the distance between the location of the user in their previous successful authentication and current authentication infers that the user had to travel at a speed greater than 1000 kilometers per hour. This condition is marked as fulfilled, only if:
            Location data is available for the current and previous IP address of the user.
            This is not the first transaction that the user has performed.
            The userâ€™s previous successful transaction was performed less than 24 hours ago.
            The user moved a distance of at least 100 kilometers. Thus, even if the user moved very fast, but moved only a distance of 90 kilometers, the condition is not fulfilled.
            The user moved at a speed greater than 1000 kilometers per hour.
        estimatedSpeed:
          type: number
          description: The calculated travel speed in units of kilometers per hour.
        anonymousNetworkDetected:
          type: boolean
          description: A boolean that specifies whether the current authentication originated from an anonymous network (for example, proxy or VPN).
        country:
          type: string
          description: A string that specifies the country related to current transaction from the IP address.
        state:
          type: string
          description: A string that specifies the state related to current transaction from the IP address.
        city:
          type: string
          description: A string that specifies the city related to current transaction from the IP address.
        longitude:
          type: number
          description: A double-precision floating point that specifies the longitude related to current transaction from the IP address. Values range from -90 to 90.
        latitude:
          type: number
          description: A double-precision floating point that specifies the latitude related to current transaction from the IP address. Values range from -180 to 180.
        previousSuccessfulTransaction:
          type: object
          properties:
            anonymousNetworkDetected:
              type: boolean
              description: A boolean that specifies whether an anonymous network was detected. Information is available twenty-four hours after the last successful transaction.
            country:
              type: string
              description: A string that specifies the country of the IP address involved in the transaction. Information is available twenty-four hours after the last successful transaction.
            state:
              type: string
              description: A string that specifies the state of the IP address involved in the transaction. Information is available twenty-four hours after the last successful transaction.
            city:
              type: string
              description: A string that specifies the city of the IP address involved in the transaction. Information is available twenty-four hours after the last successful transaction.
            ip:
              type: string
              description: A string that specifies the IP address involved in the transaction. Information is available twenty-four hours after the last successful transaction.
            timestamp:
              type: string
              description: A date that specifies the timestamp of the transaction. Information is available twenty-four hours after the last successful transaction.
        userBasedRiskBehavior:
          type: object
          properties:
            level:
              type: string
              enum: [LOW, MEDIUM, HIGH]
              description: A string that specifies the risk score calculated for the user behavior for all transactions associated with the accessing device, and for the current authentication attempt. Options are LOW, MEDIUM, and HIGH. This information is available only if customers have agreed to data consent and the intelligence.allowDataConsent property in the PingOne license is set to true.
            reason:
              type: string
              description: A string that describes the reason (or reasons) provided for the user behavior risk score classification (for example, the operating system or browser type used by the device, and country in which the accessing device is located). Each reason is classified as Unusual, to indicate how much it deviates from normal user behavior, and its effect in calculating the overall user behavior risk score.
        userRiskBehavior:
          type: object
          properties:
            level:
              type: string
              enum: [LOW, MEDIUM, HIGH]
              description: A string that specifies the risk score calculated for the user behavior within the organization associated with the accessing device, and for the current authentication attempt. Options are LOW, MEDIUM, and HIGH. This information is available only if customers have agreed to data consent and the intelligence.allowDataConsent property in the PingOne license is set to true.
            reason:
              type: string
              description: A string that describes the reason (or reasons) provided for the user behavior risk score classification within the organization (for example, the operating system or browser type used by the device, and country in which the accessing device is located). Each reason is classified as Unusual or Very Unusual, to indicate how much it deviates from normal user behavior, and its effect in calculating the overall user behavior risk score.
    RiskEvaluationEvent:
      type: object
      properties:
        browser:
          type: object
          description: An object that specifies the browser fingerprint attributes. Browser data can be retrieved using browser fingerprint JS. For more information, see Overview of the PingOne Risk Integration Kit.
          properties:
            userAgent:
              type: string
            cookie:
              type: string
            language:
              type: string
            colorDepth:
              type: number
            deviceMemory:
              type: number
            hardwareConcurrency:
              type: number
            screenResolution:
              type: array
              items:
                type: number
            availableScreenResolution:
              type: array
              items:
                type: number
            timezoneOffset:
              type: number
            timezone:
              type: string
            sessionStorage:
              type: boolean
            localStorage:
              type: boolean
            indexedDb:
              type: boolean
            addBehaviour:
              type: object
            openDatabase:
              type: boolean
            cpuClass:
              type: string
            platform:
              type: string
            plugins:
              type: array
              items:
                type: object
            webglVendorAndRenderer:
              type: string
            webgl:
              type: array
              items:
                type: string
            adBlock:
              type: boolean
            hasLiedLanguages:
              type: boolean
            hasLiedResolution:
              type: boolean
            hasLiedOs:
              type: boolean
            hasLiedBrowser:
              type: boolean
            touchSupport:
              type: array
              items:
                type: string
            fonts:
              type: array
              items:
                type: string
            audio:
              type: string
        completionStatus:
          type: string
          enum: [FAILED, IN_PROGRESS, SUCCESS]
          description: A string that specifies the state of the transaction. Options are FAILED, IN_PROGRESS, and SUCCESS. If a value is not provided, the value defaults to IN_PROGRESS. The value of this property can be changed only if its current state is IN_PROGRESS.
        evaluatedFactors:
          type: object
          properties:
            status:
              type: string
              enum: [FAILED, IN_PROGRESS, SUCCESS]
              description: A string that specifies the state of the transaction. Options are FAILED, IN_PROGRESS, and SUCCESS.
            type:
              type: string
              description: A string that specifies the transaction type.
        ip:
          type: string
          description: A string that specifies the origin IP address of the authentication flow. This is a required property.
        flow:
          type: object
          properties:
            type:
              type: string
              enum: [AUTHENTICATION]
              description: A string that specifies the flow type for the event. The only option (and default) is AUTHENTICATION.
        origin:
          type: string
          description: A string that specifies the calling service.
        session:
          type: object
          properties:
            id:
              type: string
              description: A string that specifies a unique session ID associated with the event.
          required:
            - id
        targetResource:
          type: object
          properties:
            id:
              type: string
              description: A string that specifies the ID of the target application.
            name:
              type: string
              description: A string that specifies the name of the target application.
        user:
          type: object
          properties:
            id:
              type: string
              description: A string that specifies the ID of the user associated with the event (maximum size 1024 characters). This is a required property.
            name:
              type: string
              description: A string that specifies the name of the user associated with the event (maximum size 1024 characters).
            type:
              type: string
              enum: [EXTERNAL]
              description: A string that specifies the type of user associated with the event. Options are EXTERNAL. This is a required property.
            groups:
              type: array
              description: An array of group names.
              items:
                type: object
                properties:
                  name:
                    type: string
                    description: A string that specifies the name of the group (maximum size 1024 characters).
          required:
            - id
            - type
        sharingType:
          type: string
          enum: [UNSPECIFIED, SHARED, PRIVATE]
          description: A string that specifies the device sharing type. Options are UNSPECIFIED, SHARED, and PRIVATE.
      required:
        - ip
        - user
    RiskEvaluationResult:
      type: object
      properties:
        type:
          type: string
          readOnly: true
          enum: [VALUE]
          description: A string that specifies the risk evaluation result type. Options are VALUE.
        level:
          type: string
          readOnly: true
          enum: [HIGH, MEDIUM, LOW]
          description: A string that specifies the risk evaluation result level. Options are HIGH, MEDIUM, and LOW.
        value:
          type: string
          readOnly: true
          description: A string that specifies any custom attribute the administrator defines.
    RiskPolicySet:
      type: object
      properties:
        createdAt:
          type: string
          readOnly: true
          description: The time the resource was created (format ISO-8061).
        default:
          type: boolean
          description: A boolean that specifies whether this risk policy set is the environment's default risk policy set, which is used whenever an explicit policySet ID is not specified in the risk policy evaluation request. If this property is not specified, the value defaults to false, and this risk policy set is not regarded as the default risk policy set for the environment. When this property is set to true (in PUT or POST requests), the default property of all other risk policy sets in the environment is set to false.
        defaultResult:
          $ref: '#/components/schemas/RiskPolicyResult'
          description: A result object that specifies the default result returned if none of the conditions in the policy set are evaluated to true. At this time, the defaultResultLevel value must be LOW.
        description:
          type: string
          description: A string that specifies a description for this policy set. This is an optional property. Valid characters consist of any Unicode letter, mark (for example, accent, umlaut), numeric character, punctuation character, or space. Maximum size is 1024 characters.
        environment:
          $ref: '#/components/schemas/ObjectEnvironment'
        id:
          type: string
          readOnly: true
          description: A string that specifies the resourceâ€™s unique identifier.
        name:
          type: string
          description: A string that specifies a name for this policy set. Valid characters consist of any Unicode letter, mark (for example, accent, umlaut), numeric character, forward slash, dot, apostrophe, underscore, space, or hyphen. Maximum size is 256 characters.
        riskPolicies:
          type: array
          description: An array of policies related to this policy set.
          items:
            type: object
            properties:
              condition:
                type: object
                description: The condition logic that determines when a policy is evaluated to true and when it is evaluated to false.
                properties:
                  contains:
                    type: string
                  ipRange:
                    type: array
                    items:
                      type: string
                  value:
                    type: string
                  equals:
                    oneOf:
                    - type: string
                    - type: boolean
                  aggregatedWeights:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: string
                        weight:
                          type: integer
                      required:
                        - value
                        - weight
                  between:
                    type: object
                    properties:
                      minScore:
                        type: integer
                      maxScore:
                        type: integer
                    required:
                      - minScore
                      - maxScore
              createdAt:
                type: string
                readOnly: true
                description: The time the resource was first created (format ISO-8061).
              description:
                type: string
                description: A string that specifies a description for this risk policy. This is an optional property. Valid characters consist of any Unicode letter, mark (for example, accent, umlaut), numeric character, punctuation character, or space. Maximum size is 1024 characters.
              environment:
                $ref: '#/components/schemas/ObjectEnvironment'
              id:
                type: string
                readOnly: true
                description: A string that specifies the resourceâ€™s unique identifier.
              name:
                type: string
                description: A string that specifies a name for this risk policy. Valid characters consist of any Unicode letter, mark (for example, accent, umlaut), numeric character, forward slash, dot, apostrophe, underscore, space, or hyphen. Maximum size is 256 characters.
              priority:
                type: integer
                description: An integer that specifies priority of the policy inside a risk policy set, designating which policy should run first. This is a read-only value. The priority is determined by the order in which policies are listed in the policy set. The first policy in the list is assigned priority 1 and is evaluated first. The next policy in the list is assigned priority 2 and so on.
              result:
                $ref: '#/components/schemas/RiskPolicyResult'
                description: A result object that specifies the result returned if the policy is evaluated as true. If several policies are evaluated as true, the result related to the highest priority policy is returned. for more information, see the Result attribute data model in the Risk Evaluations topic.
              updatedAt:
                type: string
                readOnly: true
                description: The time the resource was last updated (format ISO-8061).
            required:
              - name
              - result
              - condition
        updatedAt:
          type: string
          readOnly: true
          description: The time the resource was last updated (format ISO-8061).
      required:
        - name
    RiskPolicyResult:
      type: object
      properties:
        level:
          type: string
          enum: [LOW, MEDIUM, HIGH]
        type:
          type: string
          enum: [VALUE]
        value:
          type: string
      required:
        - level
    RiskPredictor:
      type: object
      properties:
        id:
          type: string
          readOnly: true
          description: A string that specifies the resourceâ€™s unique identifier.
        name:
          type: string
          description: A string type. A unique, friendly name for the predictor. This name is displayed in the Risk Policies UI, when the admin is asked to define the overrides and weights.
        compactName:
          type: string
          description: A string type. A unique name for the predictor. This property is immutable; it cannot be modified after initial creation. The value must be alpha-numeric, with no special characters or spaces. This name is used in the API both for policy configuration, and in the Risk Evaluation response (under details).
        type:
          type: string
          enum: [VELOCITY, USER_RISK_BEHAVIOR, MAP]
          description: An enum type. This can be either VELOCITY, USER_RISK_BEHAVIOR, or MAP
        description:
          type: string
          description: A string type. This specifies the desription of the risk predictor. Maximum length is 1024 characters.
        createdAt:
          type: string
          readOnly: true
          description: The time the resource was created.
        updatedAt:
          type: string
          readOnly: true
          description: The time the resource was updated.
        default:
          type: object
          properties:
            weight:
              type: integer
              description: An integer type. This specifies the weight assigned to the risk predictor in a new policy by default.
            result:
              type: object
              description: >-
                This specifies the result assigned to the predictor if the predictor could not be calculated during the risk evaluation. If this field is not provided, and the predictor could not be calculated during risk evaluation, the following options are:
                If the predictor is used in an override, the override is skipped.
                In the weighted policy, the predictor will have a weight of 0.
              properties:
                level:
                  type: string
                  enum: [HIGH,MEDIUM,LOW]
                  description: A string that identifies the risk level. Options are HIGH, MEDIUM, and LOW.
                type:
                  type: string
                  enum: [VALUE]
              required:
                - level
          required:
            - weight
            - result
        map:
          type: object
          description: An object that defines the mapping of risk levels for the list of all results.
          properties:
            high:
              $ref: '#/components/schemas/RiskPredictorItemMap'
            medium:
              $ref: '#/components/schemas/RiskPredictorItemMap'
            low:
              $ref: '#/components/schemas/RiskPredictorItemMap'
      required:
        - name
        - compactName
        - type
    RiskPredictorItemMap:
      type: object
      properties:
        contains:
          type: string
        ipRange:
          type: array
          description: List of CIDRs to include
          items:
            type: string
        between:
          type: object
          description: Minimum and maximum boundaries
          properties:
            minScore:
              type: number
            maxScore:
              type: number
          required:
            - minScore
            - maxScore
        list:
          type: array
          description: An array that specifies the list of entities that represent the risk conditions.
          items:
            type: string
      required:
        - contains
security:
  - bearer: []
tags:
  - name: Risk Management
  - name: Risk Policies
  - name: Risk Evaluations
  - name: Risk Advanced Predictors
paths:
  /v1/environments/{environmentID}/riskPolicySets:
    post:
      tags:
        - Risk Policies
      summary: CREATE Risk Policy Set
      operationId: createRiskPolicySet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RiskPolicySet'
              example:
                name: Example Policy
                description: This is an example policy.
                defaultResult:
                  level: Low
                riskPolicies:
                  - name: GEOVELOCITY_ANOMALY
                    result:
                      level: HIGH
                    condition:
                      value: ${details.impossibleTravel}
                      equals: true
                  - name: MEDIUM_WEIGHTED_POLICY
                    result:
                      level: MEDIUM
                    condition:
                      aggregatedWeights:
                        - value: ${details.aggregatedWeights.anonymousNetwork}
                          weight: 8
                        - value: ${details.aggregatedWeights.geoVelocity}
                          weight: 4
                        - value: ${details.aggregatedWeights.ipRisk}
                          weight: 8
                        - value: ${details.aggregatedWeights.ipVelocityByUser}
                          weight: 5
                        - value: ${details.aggregatedWeights.userRiskBehavior}
                          weight: 10
                        - value: ${details.aggregatedWeights.userVelocityByIp}
                          weight: 5
                      between:
                        minScore: 40
                        maxScore: 70
                  - name: HIGH_WEIGHTED_POLICY
                    result:
                      level: HIGH
                    condition:
                      aggregatedWeights:
                        - value: ${details.aggregatedWeights.anonymousNetwork}
                          weight: 8
                        - value: ${details.aggregatedWeights.geoVelocity}
                          weight: 4
                        - value: ${details.aggregatedWeights.ipRisk}
                          weight: 8
                        - value: ${details.aggregatedWeights.ipVelocityByUser}
                          weight: 5
                        - value: ${details.aggregatedWeights.userRiskBehavior}
                          weight: 10
                        - value: ${details.aggregatedWeights.userVelocityByIp}
                          weight: 5
                      between:
                        minScore: 70
                        maxScore: 100
      parameters:
        - name: environmentID
          in: path
          schema:
            type: string
          required: true
      responses:
        '401':
          description: Unauthorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
        '201':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiskPolicySet'
    get:
      tags:
        - Risk Policies
      summary: READ Risk Policy Sets
      operationId: readRiskPolicySets
      parameters:
        - name: environmentID
          in: path
          schema:
            type: string
          required: true
      responses:
        '401':
          description: Unauthorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityArray'
  /v1/environments/{environmentID}/riskPolicySets/{riskPolicySetID}:
    get:
      tags:
        - Risk Policies
      summary: READ One Risk Policy Set
      operationId: readOneRiskPolicySet
      parameters:
        - name: environmentID
          in: path
          schema:
            type: string
          required: true
        - name: riskPolicySetID
          in: path
          schema:
            type: string
          required: true
      responses:
        '401':
          description: Unauthorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiskPolicySet'
    put:
      tags:
        - Risk Policies
      summary: UPDATE Risk Policy Set
      operationId: updateRiskPolicySet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RiskPolicySet'
              example:
                name: Example Policy
                description: This is an example policy.
                defaultResult:
                  level: Low
                riskPolicies:
                  - name: GEOVELOCITY_ANOMALY
                    result:
                      level: HIGH
                    condition:
                      value: ${details.impossibleTravel}
                      equals: true
                  - name: MEDIUM_WEIGHTED_POLICY
                    result:
                      level: MEDIUM
                    condition:
                      aggregatedWeights:
                        - value: ${details.aggregatedWeights.anonymousNetwork}
                          weight: 8
                        - value: ${details.aggregatedWeights.geoVelocity}
                          weight: 4
                        - value: ${details.aggregatedWeights.ipRisk}
                          weight: 8
                        - value: ${details.aggregatedWeights.ipVelocityByUser}
                          weight: 5
                        - value: ${details.aggregatedWeights.userRiskBehavior}
                          weight: 10
                        - value: ${details.aggregatedWeights.userVelocityByIp}
                          weight: 5
                      between:
                        minScore: 40
                        maxScore: 80
                  - name: HIGH_WEIGHTED_POLICY
                    result:
                      level: HIGH
                    condition:
                      aggregatedWeights:
                        - value: ${details.aggregatedWeights.anonymousNetwork}
                          weight: 8
                        - value: ${details.aggregatedWeights.geoVelocity}
                          weight: 4
                        - value: ${details.aggregatedWeights.ipRisk}
                          weight: 8
                        - value: ${details.aggregatedWeights.ipVelocityByUser}
                          weight: 5
                        - value: ${details.aggregatedWeights.userRiskBehavior}
                          weight: 10
                        - value: ${details.aggregatedWeights.userVelocityByIp}
                          weight: 5
                      between:
                        minScore: 80
                        maxScore: 100
      parameters:
        - name: environmentID
          in: path
          schema:
            type: string
          required: true
        - name: riskPolicySetID
          in: path
          schema:
            type: string
          required: true
      responses:
        '401':
          description: Unauthorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiskPolicySet'
    delete:
      tags:
        - Risk Policies
      summary: 'DELETE Risk Policy Set '
      operationId: deleteRiskPolicySet
      parameters:
        - name: environmentID
          in: path
          schema:
            type: string
          required: true
        - name: riskPolicySetID
          in: path
          schema:
            type: string
          required: true
      responses:
        '401':
          description: Unauthorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
        '204':
          description: Successful response
  /v1/environments/{environmentID}/riskEvaluations:
    post:
      tags:
        - Risk Evaluations
      summary: CREATE Risk Evaluation
      operationId: createRiskEvaluation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RiskEvaluation'
              example:
                event:
                  completionStatus: SUCCESS
                  targetResource:
                    id: 969e4a59-5cf9-44c3-a1ba-9f392bf7f622
                    name: Jira
                  ip: 156.35.85.124
                  flow:
                    type: AUTHENTICATION
                  session:
                    id: 31618b01-08cd-4bee-b0d3-90b895671bb4
                  user:
                    id: john
                    name: John DeMock
                    type: EXTERNAL
                    groups:
                      - name: dev
                      - name: sre
                  sharingType: SHARED
                  browser:
                    userAgent: >-
                      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6)
                      AppleWebKit/537.36 (KHTML, like Gecko)
                      Chrome/80.0.3987.122 Safari/537.36
                    language: en
                    colorDepth: 24
                    deviceMemory: 8
                    hardwareConcurrency: 8
                    screenResolution:
                      - 900
                      - 1440
                    availableScreenResolution:
                      - 877
                      - 1380
                    timezoneOffset: -120
                    timezone: Asia/Jerusalem
                    sessionStorage: true
                    localStorage: true
                    indexedDb: true
                    addBehaviour: null
                    openDatabase: true
                    cpuClass: not available
                    platform: MacIntel
                    plugins:
                      - - Chrome PDF Plugin
                        - Portable Document Format
                        - - application x-google-chrome-pdf
                          - pfg
                      - - Chrome PDF Viewer
                        - - application x-google-chrome-pdf
                          - pdf
                    webglVendorAndRenderer: Intel Inc.~Intel Iris Pro OpenGL Engine
                    webgl:
                      - webgl aliased line width range:[1, 1]
                      - webgl alpha bits:8
                      - webgl antialiasing:yes
                      - webgl blue bits:8
                      - webgl depth bits:24
                      - webgl green bits:8
                      - webgl max anisotropy:16
                    adBlock: false
                    hasLiedLanguages: false
                    hasLiedResolution: false
                    hasLiedOs: false
                    hasLiedBrowser: false
                    touchSupport:
                      - '0'
                      - 'false'
                      - 'false'
                    fonts:
                      - Arial
                      - Comic Sans MS
                      - Courier
                      - Courier New
                      - Helvetica
                    audio: '124.04345808873768'
                  origin: PF_RISK_IK
      parameters:
        - name: environmentID
          in: path
          schema:
            type: string
          required: true
      responses:
        '401':
          description: Unauthorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
        '201':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiskEvaluation'
  /v1/environments/{environmentID}/riskEvaluations/{riskEvaluationID}:
    get:
      tags:
        - Risk Evaluations
      summary: READ One Risk Evaluation
      operationId: readOneRiskEvaluation
      parameters:
        - name: environmentID
          in: path
          schema:
            type: string
          required: true
        - name: riskEvaluationID
          in: path
          schema:
            type: string
          required: true
      responses:
        '401':
          description: Unauthorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiskEvaluation'
  /v1/environments/{environmentID}/riskEvaluations/{riskEvaluationID}/event:
    put:
      tags:
        - Risk Evaluations
      summary: UPDATE Risk Evaluation
      operationId: updateRiskEvaluation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RiskEvaluationEvent'
              example:
                completionStatus: SUCCESS
      parameters:
        - name: environmentID
          in: path
          schema:
            type: string
          required: true
        - name: riskEvaluationID
          in: path
          schema:
            type: string
          required: true
      responses:
        '401':
          description: Unauthorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiskEvaluation'
  /v1/environments/{environmentID}/riskPredictors:
    post:
      tags:
        - Risk Advanced Predictors
      summary: CREATE Risk Predictor
      operationId: createRiskPredictor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RiskPredictor'
              example:
                name: My Risk Predictor
                compactName: riskPred
                map:
                  high:
                    list: [
                      Dangerous,
                      Insanely Dangerous,
                      Unspeakably Dangerous
                    ]
                    contains: ${event.danger.type}
                  medium:
                    list: [
                      Kinda Dangerous
                    ]
                    contains: ${event.danger.type}
                  low:
                    list: [
                      Kinda Safe,
                      Safe
                    ]
                    contains: ${event.danger.type}
                type: MAP
                default:
                  weight: 5
                  result:
                    level: HIGH
                    type: VALUE
      parameters:
        - name: environmentID
          in: path
          schema:
            type: string
          required: true
      responses:
        '401':
          description: Unauthorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
        '201':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiskPredictor'
    get:
      tags:
        - Risk Advanced Predictors
      summary: READ All Risk Predictors
      operationId: readAllRiskPredictors
      parameters:
        - name: environmentID
          in: path
          schema:
            type: string
          required: true
      responses:
        '401':
          description: Unauthorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityArray'
  /v1/environments/{environmentID}/riskPredictors/{riskPredictorID}:
    get:
      tags:
        - Risk Advanced Predictors
      summary: READ One Risk Predictor
      operationId: readOneRiskPredictor
      parameters:
        - name: environmentID
          in: path
          schema:
            type: string
          required: true
        - name: riskPredictorID
          in: path
          schema:
            type: string
          required: true
      responses:
        '401':
          description: Unauthorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiskPredictor'
    put:
      tags:
        - Risk Advanced Predictors
      summary: UPDATE Risk Predictor
      operationId: updateRiskPredictor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RiskPredictor'
              example:
                name: My Risk Predictor
                compactName: riskPred
                map:
                  high:
                    list: [
                      Dangerous,
                      Insanely Dangerous,
                      Unspeakably Dangerous
                    ]
                    contains: ${event.danger.type}
                  medium:
                    list: [
                      Kinda Dangerous
                    ]
                    contains: ${event.danger.type}
                  low:
                    list: [
                      Kinda Safe,
                      Safe
                    ]
                    contains: ${event.danger.type}
                type: MAP
                default:
                  weight: 5
                  result:
                    level: HIGH
                    type: VALUE
      parameters:
        - name: environmentID
          in: path
          schema:
            type: string
          required: true
        - name: riskPredictorID
          in: path
          schema:
            type: string
          required: true
      responses:
        '401':
          description: Unauthorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiskPredictor'
    delete:
      tags:
        - Risk Advanced Predictors
      summary: DELETE Risk Advanced Predictor
      operationId: deleteRiskAdvancedPredictor
      parameters:
        - name: environmentID
          in: path
          schema:
            type: string
          required: true
        - name: riskPredictorID
          in: path
          schema:
            type: string
          required: true
      responses:
        '401':
          description: Unauthorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
        '204':
          description: Successful response
